require File.join( File.dirname(__FILE__), 'model.rb' )
require File.join( File.dirname(__FILE__), 'generator', 'driver.rb' )
require File.join( File.dirname(__FILE__), 'generator', 'common.rb' )
require File.join( File.dirname(__FILE__), 'generator', 'interpreter.rb' )
require File.join( File.dirname(__FILE__), 'generator', 'assembler.rb' )
require File.join( File.dirname(__FILE__), 'generator', 'disassembler.rb' )